#include "TableTennisX3_Receiver.h"

void PinSettings( void ) {
    SYS->GPA_MFPL |= ( SYS_GPA_MFPL_PA2MFP_UART1_RXD | SYS_GPA_MFPL_PA3MFP_UART1_TXD | SYS_GPA_MFPL_PA4MFP_GPIO | SYS_GPA_MFPL_PA5MFP_GPIO | SYS_GPA_MFPL_PA6MFP_GPIO );

    SYS->GPA_MFPH |= ( SYS_GPA_MFPH_PA8MFP_GPIO | SYS_GPA_MFPH_PA9MFP_GPIO | SYS_GPA_MFPH_PA15MFP_UART0_TXD | SYS_GPA_MFPH_PA14MFP_UART0_RXD );

    SYS->GPB_MFPL |= ( SYS_GPB_MFPL_PB0MFP_SPI1_MOSI0 | SYS_GPB_MFPL_PB1MFP_GPIO | SYS_GPB_MFPL_PB2MFP_SPI1_CLK | SYS_GPB_MFPL_PB3MFP_SPI1_SS0 | SYS_GPB_MFPL_PB4MFP_GPIO | SYS_GPB_MFPL_PB5MFP_GPIO );

    SYS->GPC_MFPL |= ( SYS_GPC_MFPL_PC0MFP_SPI0_SS0 | SYS_GPC_MFPL_PC1MFP_SPI0_CLK | SYS_GPC_MFPL_PC2MFP_SPI0_MISO0 | SYS_GPC_MFPL_PC3MFP_SPI0_MOSI0 );

    SYS->GPF_MFPL |= ( SYS_GPF_MFPL_PF0MFP_ICE_DAT | SYS_GPF_MFPL_PF1MFP_ICE_CLK | SYS_GPF_MFPL_PF2MFP_XT1_OUT | SYS_GPF_MFPL_PF3MFP_XT1_IN | SYS_GPF_MFPL_PF7MFP_GPIO );
}

void ClkSettings( void ) {
    CLK_EnableXtalRC( CLK_PWRCTL_HXTEN_Msk );
    while ( CLK_WaitClockReady( CLK_STATUS_HXTSTB_Msk ) == false ) {};
    CLK_SetHCLK( CLK_CLKSEL0_HCLKSEL_HXT, CLK_HCLK_CLK_DIVIDER( 1 ) );

    CLK_SetModuleClock( UART0_MODULE, CLK_CLKSEL1_UART0SEL_HXT, CLK_UART0_CLK_DIVIDER( 1 ) );
    CLK_SetModuleClock( UART1_MODULE, CLK_CLKSEL2_UART1SEL_HXT, CLK_UART0_CLK_DIVIDER( 1 ) );
    CLK_SetModuleClock( SPI0_MODULE, CLK_CLKSEL1_SPI0SEL_HXT, 0);
    CLK_SetModuleClock( SPI1_MODULE, CLK_CLKSEL2_SPI1SEL_HXT, 0);
}

void UartSettings(void){
    CLK_EnableModuleClock(UART0_MODULE);
    CLK_EnableModuleClock(UART1_MODULE);

    UART_Open(UART0, 115200);
    UART_Open(UART1, 115200);

    UART_SetTimeoutCnt(UART0, 0xFF);
    UART_SetTimeoutCnt(UART1, 0xFF);

    UART_EnableInt(UART0, UART_INTEN_RXTOIEN_Msk | UART_INTEN_RDAIEN_Msk);
    UART_EnableInt(UART1, UART_INTEN_RXTOIEN_Msk | UART_INTEN_RDAIEN_Msk);
}

void SpiSettings(void){
    CLK_EnableModuleClock(SPI0_MODULE);
    CLK_EnableModuleClock(SPI1_MODULE);
    SPI_Open( SPI0, SPI_MASTER, SPI_MODE_0, 8, 10000000 );
    SPI_Open( SPI1, SPI_MASTER, SPI_MODE_0, 8, 10000000 );
}
